# CodeFactor Configuration
# https://docs.codefactor.io/common-tasks/ignoring-files

version: '1.0'

# Exclude educational, generated and config folders from analysis
exclude_paths:
  - 'base/*'
  - 'assets/*'
  - 'public/*'
  - 'dist/*'
  - 'node_modules/*'
  - 'coverage/*'
  - '.husky/*'
  - '.github/*'
  - '.vscode/*'
  - 'src/data/*'
  - '*.config.js'
  - '*.config.cjs'
  - '*.config.mjs'
  - '*.test.js'
  - '*.spec.js'

# Disable checks that are not relevant for this project
checks:
  duplication:
    enabled: false
  complexity:
    threshold: 20
